logging:
  level:
    root: ERROR
    io.mikael: DEBUG

spring.jackson.serialization.INDENT_OUTPUT: true
management.context-path: /manage

server:
  port: 8080

---
spring.profiles: test

server.address: 127.0.0.1
server.port: 0
management.port: -1
